#!/usr/bin/env bash
# Script to install and configure HAProxy on lb-01 server should be created
# Configure HAProxy to send traffic to web-01 and web-02 servers
# Requests distribution using a roundrobin algorithm
# Make sure that HAProxy can be managed via an init script
# Install and configure HAproxy on my lb-01 server.
sudo apt-get -y update
apt-get -y install haproxy

# edit config file
server_config=\
"
frontend Tseyi-frontend
        bind *:80
        mode http
        default_backend Tseyi-backend
backend Tseyi-backend
        balance roundrobin
        server 134946-web-01 100.25.198.131:80 check
        server 134946-web-02 54.173.246.197:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
