#!/bin/bash                                                                                                                                              drwxr-xr-x 4 root root  60 Aug 31 07:13 ..                                                                                                               
                                                                                             

